name: Deploy to EC2 ☁️

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🤖
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image 🐳
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
          DOCKER_IMAGE_TAG: latest
        run: |
          docker buildx create --use
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx build --file ./Dockerfile --platform linux/amd64 -t $DOCKER_USERNAME/landing:$DOCKER_IMAGE_TAG --push .

      - name: SSH Deploy 📔
        env:
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
          ROOT: Landing_Page
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_PEM_KEY" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem

          # Replace "path/to/your/docker-compose.yml" with your actual Docker Compose file path
          scp -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no -r ./docker-compose.yml $EC2_USERNAME@$EC2_IP_ADDRESS:~/$ROOT/.
          sudo ssh -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_IP_ADDRESS "sudo docker-compose -f ~/$ROOT/docker-compose.yml up -d"